//
//  UIColor+Fripple.swift
//
//  Generated by Zeplin on 8/18/15.
//  Copyright (c) 2015 __Fripple__. All rights reserved.
//

import UIKit

extension UIColor {
    class func untMangoColor() -> UIColor {
        return UIColor(red: 253.0 / 255.0, green: 183.0 / 255.0, blue: 53.0 / 255.0, alpha: 1.0)
    }

    class func untPaleTealColor() -> UIColor {
        return UIColor(red: 145.0 / 255.0, green: 206.0 / 255.0, blue: 158.0 / 255.0, alpha: 1.0)
    }

    class func untNastyGreenColor() -> UIColor {
        return UIColor(red: 130.0 / 255.0, green: 189.0 / 255.0, blue: 68.0 / 255.0, alpha: 1.0)
    }

    class func untPurplishPinkColor() -> UIColor {
        return UIColor(red: 199.0 / 255.0, green: 93.0 / 255.0, blue: 163.0 / 255.0, alpha: 1.0)
    }

    class func untMediumPinkColor() -> UIColor {
        return UIColor(red: 244.0 / 255.0, green: 96.0 / 255.0, blue: 195.0 / 255.0, alpha: 1.0)
    }

    class func untCeriseColor() -> UIColor {
        return UIColor(red: 233.0 / 255.0, green: 21.0 / 255.0, blue: 139.0 / 255.0, alpha: 1.0)
    }

    class func untLipstickColor() -> UIColor {
        return UIColor(red: 220.0 / 255.0, green: 28.0 / 255.0, blue: 135.0 / 255.0, alpha: 1.0)
    }

    class func untWisteriaColor() -> UIColor {
        return UIColor(red: 144.0 / 255.0, green: 141.0 / 255.0, blue: 196.0 / 255.0, alpha: 1.0)
    }

    class func untDarkLilacColor() -> UIColor {
        return UIColor(red: 143.0 / 255.0, green: 100.0 / 255.0, blue: 162.0 / 255.0, alpha: 1.0)
    }

    class func untPurplyColor() -> UIColor {
        return UIColor(red: 100.0 / 255.0, green: 80.0 / 255.0, blue: 180.0 / 255.0, alpha: 1.0)
    }

    class func untDarkSkyBlueColor() -> UIColor {
        return UIColor(red: 54.0 / 255.0, green: 183.0 / 255.0, blue: 236.0 / 255.0, alpha: 1.0)
    }

    class func untCeruleanColor() -> UIColor {
        return UIColor(red: 8.0 / 255.0, green: 133.0 / 255.0, blue: 209.0 / 255.0, alpha: 1.0)
    }

    class func untTurquoiseBlueColor() -> UIColor {
        return UIColor(red: 8.0 / 255.0, green: 166.0 / 255.0, blue: 209.0 / 255.0, alpha: 1.0)
    }

    class func untNiceBlueColor() -> UIColor {
        return UIColor(red: 19.0 / 255.0, green: 96.0 / 255.0, blue: 190.0 / 255.0, alpha: 1.0)
    }
    
    class func untBkgdBlueColor() -> UIColor {
        return UIColor(red: 20.0 / 255.0, green: 120.0 / 255.0, blue: 210.0 / 255.0, alpha: 1.0)
    }
}
